### ISSUE TITLE
使用新版本跑示例程序出错

### ISSUE THREAD

**Issue by yinhang-e5b0b9e888aa** [Angel-ML/PyTorch-On-Angel#102]
之前用0.2版本没有这个错误，不知道是因为更新了什么导致的

`	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1168)
	at com.tencent.angel.pytorch.graph.gcn.GCN.makeGraph(GCN.scala:60)
	at com.tencent.angel.pytorch.graph.gcn.GNN.initialize(GNN.scala:99)
	at com.tencent.angel.pytorch.examples.supervised.cluster.GraphSageExample$.main(GraphSageExample.scala:150)
	at com.tencent.angel.pytorch.examples.supervised.cluster.GraphSageExample.main(GraphSageExample.scala)
Caused by: com.tencent.angel.exception.AngelException: com.tencent.angel.exception.AngelException: node id is not in range [0, 10
	at com.tencent.angel.psagent.matrix.MatrixClientImpl.get(MatrixClientImpl.java:732)
	at com.tencent.angel.spark.models.impl.PSVectorImpl.psfGet(PSVectorImpl.scala:78)
	at com.tencent.angel.pytorch.graph.gcn.GNNPSModel.readLabels2(GNNPSModel.scala:71)
	at com.tencent.angel.pytorch.graph.gcn.GraphAdjPartition.splitTrainTest(GraphPartition.scala:62)
	at com.tencent.angel.pytorch.graph.gcn.GraphAdjPartition.toSemiGCNPartition(GraphPartition.scala:49)
	at com.tencent.angel.pytorch.graph.gcn.GCN$$anonfun$4.apply(GCN.scala:54)
	at com.tencent.angel.pytorch.graph.gcn.GCN$$anonfun$4.apply(GCN.scala:54)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)`

**Comment by ouyangwen-it** [comment]
angel用的是哪个版本

**Comment by yinhang-e5b0b9e888aa** [comment]
> angel用的是哪个版本

3.2.0 release

**Comment by rachelsunrh** [comment]
这个是全部的错误日志了吗， 发一下完整错误日志吧

**Comment by rachelsunrh** [comment]
用最新的angel工程master分支的代码

**Comment by yinhang-e5b0b9e888aa** [comment]
用angel的master分支的代码可以跑过了
