### ISSUE TITLE
请问支持angel3.0么？NoClassDefFoundError：com/tencent/angel/ml/matrix/RowType

### ISSUE THREAD

**Issue by wjlight** [Angel-ML/PyTorch-On-Angel#14]
跑demo的时候，发现

> Exception in thread "main" java.lang.NoClassDefFoundError: com/tencent/angel/ml/matrix/RowType
        at com.tencent.angel.pytorch.model.TorchParams.<init>(TorchParams.scala:29)
        at com.tencent.angel.pytorch.model.ParTorchModel.init(ParTorchModel.scala:69)
        at com.tencent.angel.pytorch.examples.ClusterExample$.main(ClusterExample.scala:68)
        at com.tencent.angel.pytorch.examples.ClusterExample.main(ClusterExample.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.tencent.angel.ml.matrix.RowType
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 more

这个类在44b7c476d0c6b2aab7399f5200f64c44aa973fb5这次提交的时候修改路径了，到angel-math-0.1.0.jar里去了，请问该怎么处理？

**Comment by ouyangwen-it** [comment]
目前pytrch on angel还不支持3.0，依赖2.3.0或者2.3.1

**Comment by wjlight** [comment]
请问下，什么时候会支持angel3呢？

**Comment by ouyangwen-it** [comment]
> 请问下，什么时候会支持angel3呢？

是这样的，这个项目跑需要依赖spark，3.0已经把angel和spark on angel分开了，所以你需要跑2.3.1或者2.4.0的angel版本.

**Comment by ouyangwen-it** [comment]
> 请问下，什么时候会支持angel3呢？

目前已经能支持到3.1.0的版本了

**Comment by yinhang-e5b0b9e888aa** [comment]
> > 请问下，什么时候会支持angel3呢？
> 
> 目前已经能支持到3.1.0的版本了

 请问要使用3.0版本的Angel，应该怎么配置呢？是需要修改这个工程的pom.xml文件吗？

**Comment by ouyangwen-it** [comment]
> > > 请问下，什么时候会支持angel3呢？
> > 
> > 
> > 目前已经能支持到3.1.0的版本了
> 
> 请问要使用3.0版本的Angel，应该怎么配置呢？是需要修改这个工程的pom.xml文件吗？

直接使用branch-0.2.1分支就可以了，不需要修改配置哈
