### ISSUE TITLE
Is there any test sample data for GCN example?

### ISSUE THREAD

**Issue by leafjungle** [Angel-ML/PyTorch-On-Angel#25]
21/02/04 15:13:00 ERROR ApplicationMaster: User class threw exception: java.lang.AbstractMethodError: com.tencent.angel.pytorch.graph.gcn.GCN.org$apache$spark$ml$param$Params$_setter_$paramMap_$eq(Lorg/apache/spark/ml/param/ParamMap;)V
java.lang.AbstractMethodError: com.tencent.angel.pytorch.graph.gcn.GCN.org$apache$spark$ml$param$Params$_setter_$paramMap_$eq(Lorg/apache/spark/ml/param/ParamMap;)V
	at org.apache.spark.ml.param.Params$class.$init$(params.scala:868)
	at com.tencent.angel.pytorch.graph.gcn.GNN.<init>(GNN.scala:39)
	at com.tencent.angel.pytorch.graph.gcn.GNN.<init>(GNN.scala:46)

![image](https://user-images.githubusercontent.com/6143261/106858388-8b500100-66fc-11eb-878f-b28fb0c70f1e.png)

**Comment by leafjungle** [comment]
It may be caused by: the compile version and spark run version is different(class : org/apache/spark/ml/param/ParamMap).

But I have checked them. compile version:
    <scala.version>2.11.12</scala.version>
    <scala.binary.version>2.11</scala.binary.version>

spark version is:
![image](https://user-images.githubusercontent.com/6143261/106864316-a6bf0a00-6704-11eb-9b9f-4a8f41ddbb4c.png)

So, I am still so confused.
